In [2]:
import numpy as np

In [3]:
# генерируем дискретную величину
np.random.randint(1, 5)

4

In [4]:
np.random.randint(1, 5, 100)

array([2, 4, 4, 4, 2, 1, 3, 3, 4, 4, 1, 3, 1, 2, 2, 2, 2, 3, 2, 3, 3, 2,
       4, 4, 4, 3, 4, 3, 2, 4, 1, 3, 3, 4, 4, 4, 4, 3, 1, 4, 4, 1, 3, 2,
       4, 1, 2, 2, 1, 4, 4, 1, 4, 3, 3, 1, 2, 1, 1, 2, 2, 2, 3, 1, 3, 2,
       1, 1, 1, 3, 4, 4, 3, 4, 2, 3, 4, 1, 3, 2, 1, 2, 1, 1, 1, 2, 3, 4,
       3, 1, 4, 1, 1, 1, 4, 2, 3, 3, 1, 2])

In [5]:
# генерируем непрерывную величину
np.random.random(100)

array([0.93907142, 0.4207238 , 0.7830525 , 0.36213198, 0.40241347,
       0.80960262, 0.50948334, 0.05538276, 0.65923507, 0.12069541,
       0.57882275, 0.93707384, 0.20232117, 0.71303311, 0.28043273,
       0.39098103, 0.34837015, 0.09949862, 0.34928889, 0.63144945,
       0.93179594, 0.46316529, 0.50946628, 0.27742292, 0.85148537,
       0.82492711, 0.31278576, 0.10795469, 0.84663141, 0.57914373,
       0.49980156, 0.01149858, 0.87982254, 0.84963466, 0.97300225,
       0.47360605, 0.09857714, 0.54472903, 0.42320752, 0.76650709,
       0.86867899, 0.44238077, 0.34423161, 0.52761325, 0.47378917,
       0.79063785, 0.1641183 , 0.75481973, 0.7366378 , 0.01937444,
       0.0531937 , 0.10826777, 0.46788515, 0.87397699, 0.37209   ,
       0.341619  , 0.22478325, 0.33555498, 0.32343601, 0.02278001,
       0.50919469, 0.77490896, 0.7577859 , 0.61836466, 0.35709843,
       0.69093824, 0.23852559, 0.92763527, 0.19325383, 0.40791944,
       0.12051396, 0.47904978, 0.44028949, 0.24503754, 0.80865

In [6]:
np.random.uniform(1, 5)

4.335895339778029

In [7]:
np.random.uniform(1, 5, 100)

array([1.10568667, 2.35772595, 2.63543897, 2.24891134, 1.51021474,
       4.53052407, 3.313741  , 1.20596826, 1.77617777, 2.58762423,
       3.96038742, 2.67013566, 2.46116465, 3.27587565, 4.52289587,
       2.48931575, 2.69773333, 3.68170061, 3.19721375, 2.73120476,
       4.64167853, 3.07666073, 3.47515158, 1.70076875, 3.8990342 ,
       2.08234373, 3.63468222, 4.0459869 , 3.01014659, 4.98824767,
       3.27730359, 4.26486423, 4.13491096, 2.97523743, 1.79440399,
       3.48874205, 4.09515861, 2.86712774, 2.57781917, 1.84475008,
       3.59730151, 2.3613734 , 1.75566454, 1.60409875, 1.90183527,
       3.25912793, 4.75595683, 1.31854678, 2.85126868, 3.11941333,
       2.105153  , 3.98700728, 1.27103802, 3.48037018, 2.00358413,
       3.639756  , 2.59269215, 1.20193001, 1.87143854, 4.14614964,
       3.74098681, 3.28322639, 2.32585005, 2.18632005, 1.28605948,
       3.18032627, 3.66652857, 4.01549822, 3.26263267, 1.98424701,
       3.41202374, 3.83059298, 1.81211411, 2.24565058, 3.14795

**Задача 1.** Оценить вероятность того, что на игральной кости выпадет больше 4 очков. Сравнить с теоретической вероятностью.

In [8]:
import numpy as np
# np.random.seed(None)
trials = 1000    # Количество попыток
successes = 0    # Количество успехов

for i in range(trials):
    random_score = np.random.randint(1, 7)    # Случайное количество очков от 1 до 6
    if random_score > 4:
        successes += 1
        
p_monte_carlo = successes / trials    # Вероятность из моделирования
p = 2 / 6                             # Теоретическая вероятность

print(successes, trials, p_monte_carlo, p)

330 1000 0.33 0.3333333333333333


**Задача 1А** (опциональная). Дан квадрат, в который вписан круг (касаясь сторон квадрата). В квадрат случайным образом попадают точки. Какова вероятность, что наугад взятая точка попадёт в круг?  
_Подсказка:_ Удобно взять квардат со стороной, равной 2, и отсчитывать координаты точек от его центра.

**Задача 2.** Смоделировать стрельбу по мишени.

In [ ]:
import matplotlib.pyplot as plt

shots = 1000    # Количество выстрелов
std_dev = 1 # Стандартное отклонение (на сколько мы в среднем будем мазать)

x = np.random.normal(0, std_dev, shots) # 0 - и среднее, и мода, и медиана
y = np.random.normal(0, std_dev, shots)


plt.scatter(x, y)
# почему разброс от -3 до 3?

**Задача 3.** Графически определить распределение измеренных значений физической величины, когда измерительный прибор имеет случайную погрешность.

In [ ]:
import pandas as pd

data = pd.read_csv("data.log", sep=" ")["az"]
data.describe()

In [ ]:
data.plot()

In [ ]:
plt.hist(uni, bins=11)
plt.show()
plt.hist(normal, bins=11)
plt.show()
plt.hist(data, bins=11)
plt.show()

**Задача 4.** Рассчитать вероятность того, что пациент заражён COVID-19, если известно, что тест дал положительный результат. Сравнить с результатом моделирования.

In [9]:
prev = 0.50    # Распространённость болезни
sens = 0.95    # Чувствительность теста
spec = 0.80    # Специфичность теста

p = (sens * prev) / (sens * prev + (1 - spec) * (1 - prev))   # Теоретическая вероятность 
print(p)

0.8260869565217391


In [10]:
population = 100    # Количество испытуемых

true_pos = 0    # Количество больных с положительным тестом
false_pos = 0   # Количество здоровых с положительным тестом

for i in range(population):
    # Наугад решаем, заражён ли человек
    # для этого генерируем случайную величину от 0 до 1     
    infected = np.random.uniform() < prev
    
    # Наугад решаем, дал ли тест положительный результат 
    positive = np.random.uniform() < sens if infected else np.random.uniform() < 1 - spec
    
    if positive:
        if infected:
            true_pos += 1
        else:
            false_pos += 1
            
p_monte_carlo = true_pos / (true_pos + false_pos)    # Вероятность из моделирования
print(p_monte_carlo)

0.8833333333333333
