# Домашнее задание «Библиотека numpy. Вычислительные задачи»

## Задание 1
### Дано
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))
### Решение

In [19]:
import numpy as np

N = 10
# последовательность в обратном порядке: шаг в другую сторону должен быть -1
x = np.arange(N - 1, -1, -1)
print(x)

[9 8 7 6 5 4 3 2 1 0]


## Задание 2
### Дано
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
### Решение

In [4]:
import numpy as np

N = 5
# диагональная матрица с смещением к=0
x = np.diag(np.arange(N - 1, -1, -1), k=0)
sum_diag = 0
for i in range(N):
    sum_diag += x[i][i]
print(x, 'Сумма значений по диагонали:', sum_diag)

[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]] Сумма значений по диагонали: 10


## Задание 3
### Дано
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
### Решение

In [28]:
import numpy as np
from numpy import linalg
# коэффициенты перед переменными в матрице х, коэффициенты правой части - а
x = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
a = np.array([4, 12, -3])
# решение системы уравнений при помощи библиотеки linalg и заодно подстановка этого решения 
decision = linalg.solve(x, a)
check_it = np.allclose(np.dot(x, linalg.solve(x, a)), a )
print(decision, check_it)

[ 0.46666667  3.84444444 -5.55555556] True


## Задание 4
### Дано
В материалах занятия раздел “Задача 4 домашнего задания”

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

from IPython.display import Image
Image("user_matrix.JPG")

Матрица в виде numpy array
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats
### Решение

In [35]:
from IPython.display import Image
Image("user_matrix.JPG")

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

cosine_user = 0

next_user_stats = np.array([0, 1, 2, 0, 0, 0])
for a in users_stats:
    a_user_Length = np.linalg.norm( a )
    b_user_Length = np.linalg.norm( next_user_stats )
    cosine = np.dot( a, next_user_stats ) / ( a_user_Length * b_user_Length)
    angle = np.arccos( cosine ) * 360 / 2 / np.pi
    if cosine > cosine_user:
        cosine_user = cosine
        closest_user = a
print('Ближайший пользователь:', closest_user, 'Косинусное сходство:', cosine_user)

Ближайший пользователь: [0 1 1 0 0 0] Косинусное сходство: 0.9486832980505138
